# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_auto_20160504_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name=b'e-\xc2\xadmail'),
        ),
    ]
